use crate::ids::InputDeviceId;
use serde::{Deserialize, Serialize};
use std::collections::HashSet;

/// A physical key position, independent of layout — the thing that was actually
/// pressed. `KeyA` always means "the key in the QWERTY A position," never "the key
/// that produces the letter A" (section 4 draws this distinction explicitly). Backends
/// map their native scancode/keycode space onto this enum once, at the boundary.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[non_exhaustive]
pub enum PhysicalKey {
    KeyA, KeyB, KeyC, KeyD, KeyE, KeyF, KeyG, KeyH, KeyI, KeyJ, KeyK, KeyL, KeyM,
    KeyN, KeyO, KeyP, KeyQ, KeyR, KeyS, KeyT, KeyU, KeyV, KeyW, KeyX, KeyY, KeyZ,
    Digit0, Digit1, Digit2, Digit3, Digit4, Digit5, Digit6, Digit7, Digit8, Digit9,
    Enter, Escape, Backspace, Tab, Space,
    Minus, Equal, BracketLeft, BracketRight, Backslash, Semicolon, Quote, Grave,
    Comma, Period, Slash,
    CapsLock, ScrollLock, NumLock,
    F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12,
    PrintScreen, Pause, Insert, Home, PageUp, Delete, End, PageDown,
    ArrowRight, ArrowLeft, ArrowDown, ArrowUp,
    ControlLeft, ShiftLeft, AltLeft, SuperLeft,
    ControlRight, ShiftRight, AltRight, SuperRight,
    MediaPlayPause, MediaNextTrack, MediaPrevTrack, MediaVolumeUp, MediaVolumeDown, MediaMute,
    Compose,
    /// Escape hatch for layout-specific or vendor keys not enumerated above. Carries
    /// the backend's raw code purely for diagnostics (section 28) — never matched on
    /// by application logic.
    Other(u32),
}

/// The character/action a physical key produces *after* layout mapping — what an
/// application-level shortcut binding should compare against. Multiple physical keys
/// can map to the same logical key on some layouts, and the same physical key can map
/// to different logical keys across layouts.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[non_exhaustive]
pub enum LogicalKey {
    Character(char),
    Enter,
    Escape,
    Backspace,
    Tab,
    Space,
    CapsLock,
    ScrollLock,
    NumLock,
    Function(u8),
    PrintScreen,
    Pause,
    Insert,
    Home,
    PageUp,
    Delete,
    End,
    PageDown,
    ArrowRight,
    ArrowLeft,
    ArrowDown,
    ArrowUp,
    Control,
    Shift,
    Alt,
    Super,
    MediaPlayPause,
    MediaNextTrack,
    MediaPrevTrack,
    MediaVolumeUp,
    MediaVolumeDown,
    MediaMute,
    Compose,
    Unidentified,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum KeyAction {
    Down,
    Up,
    /// Auto-repeat while held, generated by [`KeyboardState`] — not by the backend —
    /// so repeat timing is one place, not re-derived per platform (section 4).
    Repeat,
}

/// Ctrl / Alt / Shift / Super plus the three lock keys, tracked as live state rather
/// than re-derived per event, so every [`InputEvent`](crate::event::InputEvent) can
/// carry an authoritative modifier snapshot (section 4, section 11).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct Modifiers {
    pub ctrl: bool,
    pub alt: bool,
    pub shift: bool,
    pub logo: bool,
    pub caps_lock: bool,
    pub num_lock: bool,
    pub scroll_lock: bool,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct KeyboardEvent {
    pub physical_key: PhysicalKey,
    pub logical_key: LogicalKey,
    /// Text an input-method/layout would insert, if any — punctuation and letter keys
    /// carry it, `ArrowLeft` or a bare modifier does not. Kept separate from
    /// `logical_key` so shortcut handling never has to parse text back into a key
    /// (section 4's physical → logical → text pipeline, stopping short of full IME
    /// composition which section 4 leaves to the application layer).
    pub text: Option<String>,
    pub action: KeyAction,
}

/// Maps [`PhysicalKey`] to [`LogicalKey`]/text. `UsQwerty` is the only implementation
/// today; international layouts and compose-key sequences (section 4) plug in here
/// without touching event plumbing.
pub trait KeyboardLayout: Send + Sync {
    fn name(&self) -> &str;
    fn map(&self, key: PhysicalKey, modifiers: Modifiers) -> LogicalKey;
    fn text_for(&self, logical: LogicalKey, modifiers: Modifiers) -> Option<String>;
}

pub struct UsQwertyLayout;

impl KeyboardLayout for UsQwertyLayout {
    fn name(&self) -> &str {
        "us"
    }

    fn map(&self, key: PhysicalKey, modifiers: Modifiers) -> LogicalKey {
        use LogicalKey as L;
        use PhysicalKey as P;
        let shifted = modifiers.shift ^ modifiers.caps_lock;
        match key {
            P::KeyA => char_key('a', 'A', shifted),
            P::KeyB => char_key('b', 'B', shifted),
            P::KeyC => char_key('c', 'C', shifted),
            P::KeyD => char_key('d', 'D', shifted),
            P::KeyE => char_key('e', 'E', shifted),
            P::KeyF => char_key('f', 'F', shifted),
            P::KeyG => char_key('g', 'G', shifted),
            P::KeyH => char_key('h', 'H', shifted),
            P::KeyI => char_key('i', 'I', shifted),
            P::KeyJ => char_key('j', 'J', shifted),
            P::KeyK => char_key('k', 'K', shifted),
            P::KeyL => char_key('l', 'L', shifted),
            P::KeyM => char_key('m', 'M', shifted),
            P::KeyN => char_key('n', 'N', shifted),
            P::KeyO => char_key('o', 'O', shifted),
            P::KeyP => char_key('p', 'P', shifted),
            P::KeyQ => char_key('q', 'Q', shifted),
            P::KeyR => char_key('r', 'R', shifted),
            P::KeyS => char_key('s', 'S', shifted),
            P::KeyT => char_key('t', 'T', shifted),
            P::KeyU => char_key('u', 'U', shifted),
            P::KeyV => char_key('v', 'V', shifted),
            P::KeyW => char_key('w', 'W', shifted),
            P::KeyX => char_key('x', 'X', shifted),
            P::KeyY => char_key('y', 'Y', shifted),
            P::KeyZ => char_key('z', 'Z', shifted),
            P::Digit0 => char_key('0', ')', modifiers.shift),
            P::Digit1 => char_key('1', '!', modifiers.shift),
            P::Digit2 => char_key('2', '@', modifiers.shift),
            P::Digit3 => char_key('3', '#', modifiers.shift),
            P::Digit4 => char_key('4', '$', modifiers.shift),
            P::Digit5 => char_key('5', '%', modifiers.shift),
            P::Digit6 => char_key('6', '^', modifiers.shift),
            P::Digit7 => char_key('7', '&', modifiers.shift),
            P::Digit8 => char_key('8', '*', modifiers.shift),
            P::Digit9 => char_key('9', '(', modifiers.shift),
            P::Minus => char_key('-', '_', modifiers.shift),
            P::Equal => char_key('=', '+', modifiers.shift),
            P::BracketLeft => char_key('[', '{', modifiers.shift),
            P::BracketRight => char_key(']', '}', modifiers.shift),
            P::Backslash => char_key('\\', '|', modifiers.shift),
            P::Semicolon => char_key(';', ':', modifiers.shift),
            P::Quote => char_key('\'', '"', modifiers.shift),
            P::Grave => char_key('`', '~', modifiers.shift),
            P::Comma => char_key(',', '<', modifiers.shift),
            P::Period => char_key('.', '>', modifiers.shift),
            P::Slash => char_key('/', '?', modifiers.shift),
            P::Space => L::Space,
            P::Enter => L::Enter,
            P::Escape => L::Escape,
            P::Backspace => L::Backspace,
            P::Tab => L::Tab,
            P::CapsLock => L::CapsLock,
            P::ScrollLock => L::ScrollLock,
            P::NumLock => L::NumLock,
            P::F1 => L::Function(1),
            P::F2 => L::Function(2),
            P::F3 => L::Function(3),
            P::F4 => L::Function(4),
            P::F5 => L::Function(5),
            P::F6 => L::Function(6),
            P::F7 => L::Function(7),
            P::F8 => L::Function(8),
            P::F9 => L::Function(9),
            P::F10 => L::Function(10),
            P::F11 => L::Function(11),
            P::F12 => L::Function(12),
            P::PrintScreen => L::PrintScreen,
            P::Pause => L::Pause,
            P::Insert => L::Insert,
            P::Home => L::Home,
            P::PageUp => L::PageUp,
            P::Delete => L::Delete,
            P::End => L::End,
            P::PageDown => L::PageDown,
            P::ArrowRight => L::ArrowRight,
            P::ArrowLeft => L::ArrowLeft,
            P::ArrowDown => L::ArrowDown,
            P::ArrowUp => L::ArrowUp,
            P::ControlLeft | P::ControlRight => L::Control,
            P::ShiftLeft | P::ShiftRight => L::Shift,
            P::AltLeft | P::AltRight => L::Alt,
            P::SuperLeft | P::SuperRight => L::Super,
            P::MediaPlayPause => L::MediaPlayPause,
            P::MediaNextTrack => L::MediaNextTrack,
            P::MediaPrevTrack => L::MediaPrevTrack,
            P::MediaVolumeUp => L::MediaVolumeUp,
            P::MediaVolumeDown => L::MediaVolumeDown,
            P::MediaMute => L::MediaMute,
            P::Compose => L::Compose,
            P::Other(_) => L::Unidentified,
        }
    }

    fn text_for(&self, logical: LogicalKey, _modifiers: Modifiers) -> Option<String> {
        match logical {
            LogicalKey::Character(c) => Some(c.to_string()),
            LogicalKey::Space => Some(" ".to_string()),
            _ => None,
        }
    }
}

fn char_key(lower: char, upper: char, shifted: bool) -> LogicalKey {
    LogicalKey::Character(if shifted { upper } else { lower })
}

/// Live per-keyboard state: which physical keys are held, and the derived modifier
/// snapshot every event on that device carries. One instance per keyboard device so
/// unplugging one keyboard mid-chord can't leave another keyboard's modifiers stuck
/// (section 9's "existing focus/grab state cleaned up" on device removal).
#[derive(Debug, Default)]
pub struct KeyboardState {
    pressed: HashSet<PhysicalKey>,
    modifiers: Modifiers,
}

impl KeyboardState {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn modifiers(&self) -> Modifiers {
        self.modifiers
    }

    pub fn is_pressed(&self, key: PhysicalKey) -> bool {
        self.pressed.contains(&key)
    }

    pub fn pressed_keys(&self) -> impl Iterator<Item = &PhysicalKey> {
        self.pressed.iter()
    }

    /// Returns `true` the first time a key transitions down (repeats produced by an
    /// already-held key are the backend's/compositor's concern, not double-counted
    /// here).
    pub fn note_down(&mut self, key: PhysicalKey) -> bool {
        self.update_modifier(key, true);
        self.pressed.insert(key)
    }

    pub fn note_up(&mut self, key: PhysicalKey) -> bool {
        self.update_modifier(key, false);
        self.pressed.remove(&key)
    }

    fn update_modifier(&mut self, key: PhysicalKey, is_down: bool) {
        match key {
            PhysicalKey::ControlLeft | PhysicalKey::ControlRight => self.modifiers.ctrl = is_down,
            PhysicalKey::AltLeft | PhysicalKey::AltRight => self.modifiers.alt = is_down,
            PhysicalKey::ShiftLeft | PhysicalKey::ShiftRight => self.modifiers.shift = is_down,
            PhysicalKey::SuperLeft | PhysicalKey::SuperRight => self.modifiers.logo = is_down,
            PhysicalKey::CapsLock if is_down => self.modifiers.caps_lock = !self.modifiers.caps_lock,
            PhysicalKey::NumLock if is_down => self.modifiers.num_lock = !self.modifiers.num_lock,
            PhysicalKey::ScrollLock if is_down => self.modifiers.scroll_lock = !self.modifiers.scroll_lock,
            _ => {}
        }
    }
}

/// Registry of per-device keyboard state, owned by
/// [`InputService`](crate::service::InputService).
#[derive(Debug, Default)]
pub struct KeyboardStateTable(std::collections::HashMap<InputDeviceId, KeyboardState>);

impl KeyboardStateTable {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn state_mut(&mut self, device: InputDeviceId) -> &mut KeyboardState {
        self.0.entry(device).or_default()
    }

    pub fn remove(&mut self, device: InputDeviceId) {
        self.0.remove(&device);
    }

    /// Modifier state isn't scoped to "the keyboard that produced this event" in a
    /// single-seat desktop — Ctrl held on one keyboard and a click on the mouse should
    /// still register as a Ctrl-click. [`InputService`](crate::service::InputService)
    /// ORs every connected keyboard's modifiers together for non-keyboard events.
    pub fn aggregate(&self) -> Modifiers {
        self.0.values().fold(Modifiers::default(), |mut acc, state| {
            let m = state.modifiers();
            acc.ctrl |= m.ctrl;
            acc.alt |= m.alt;
            acc.shift |= m.shift;
            acc.logo |= m.logo;
            acc.caps_lock |= m.caps_lock;
            acc.num_lock |= m.num_lock;
            acc.scroll_lock |= m.scroll_lock;
            acc
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn holding_ctrl_sets_modifier_and_releasing_clears_it() {
        let mut state = KeyboardState::new();
        assert!(!state.modifiers().ctrl);

        state.note_down(PhysicalKey::ControlLeft);
        assert!(state.modifiers().ctrl);

        state.note_up(PhysicalKey::ControlLeft);
        assert!(!state.modifiers().ctrl);
    }

    #[test]
    fn caps_lock_toggles_rather_than_tracks_held_state() {
        let mut state = KeyboardState::new();
        state.note_down(PhysicalKey::CapsLock);
        assert!(state.modifiers().caps_lock);
        state.note_up(PhysicalKey::CapsLock);
        // Releasing the key must not itself flip caps lock back off.
        assert!(state.modifiers().caps_lock);
        state.note_down(PhysicalKey::CapsLock);
        assert!(!state.modifiers().caps_lock);
    }

    #[test]
    fn note_down_reports_first_transition_only() {
        let mut state = KeyboardState::new();
        assert!(state.note_down(PhysicalKey::KeyA));
        assert!(!state.note_down(PhysicalKey::KeyA));
    }

    #[test]
    fn us_qwerty_distinguishes_physical_logical_and_text() {
        let layout = UsQwertyLayout;
        let logical = layout.map(PhysicalKey::KeyA, Modifiers::default());
        assert_eq!(logical, LogicalKey::Character('a'));
        assert_eq!(layout.text_for(logical, Modifiers::default()), Some("a".to_string()));

        let shifted = Modifiers { shift: true, ..Default::default() };
        assert_eq!(layout.map(PhysicalKey::KeyA, shifted), LogicalKey::Character('A'));

        // A non-character physical key must not fabricate text.
        let arrow = layout.map(PhysicalKey::ArrowLeft, Modifiers::default());
        assert_eq!(arrow, LogicalKey::ArrowLeft);
        assert_eq!(layout.text_for(arrow, Modifiers::default()), None);
    }

    #[test]
    fn aggregate_ors_modifiers_across_keyboards() {
        let mut table = KeyboardStateTable::new();
        let kb1 = InputDeviceId::new();
        let kb2 = InputDeviceId::new();
        table.state_mut(kb1).note_down(PhysicalKey::ControlLeft);
        table.state_mut(kb2).note_down(PhysicalKey::ShiftLeft);

        let aggregated = table.aggregate();
        assert!(aggregated.ctrl);
        assert!(aggregated.shift);
        assert!(!aggregated.alt);
    }

    #[test]
    fn removing_a_device_drops_its_state() {
        let mut table = KeyboardStateTable::new();
        let kb = InputDeviceId::new();
        table.state_mut(kb).note_down(PhysicalKey::ControlLeft);
        assert!(table.aggregate().ctrl);

        table.remove(kb);
        assert!(!table.aggregate().ctrl);
    }
}
